-- PostgreSQL schema for the unified UFO sightings database.
--
-- Translated from the SQLite schema produced by ufo-dedup. Run this against
-- a fresh `ufo_unified` database before importing rows via migrate_sqlite_to_pg.py.
--
-- IDs are BIGINT (not BIGSERIAL) because the migration script preserves the
-- original SQLite primary keys verbatim. The dedup pipeline is the only writer;
-- the web app is read-only. If you ever need to write rows from the app, switch
-- the id columns to GENERATED BY DEFAULT AS IDENTITY and create sequences.

-- =========================================================================
-- Lookup tables (small, populated first because of FK references)
-- =========================================================================

CREATE TABLE source_collection (
    id           BIGINT PRIMARY KEY,
    name         TEXT NOT NULL UNIQUE,
    display_name TEXT,
    description  TEXT,
    url          TEXT
);

CREATE TABLE source_database (
    id            BIGINT PRIMARY KEY,
    name          TEXT NOT NULL UNIQUE,
    collection_id BIGINT REFERENCES source_collection(id),
    description   TEXT,
    url           TEXT,
    copyright     TEXT,
    record_count  INTEGER
);

CREATE TABLE source_origin (
    id          BIGINT PRIMARY KEY,
    name        TEXT NOT NULL UNIQUE,
    description TEXT
);

CREATE TABLE location (
    id          BIGINT PRIMARY KEY,
    raw_text    TEXT,
    city        TEXT,
    county      TEXT,
    state       TEXT,
    country     TEXT,
    region      TEXT,
    latitude    DOUBLE PRECISION,
    longitude   DOUBLE PRECISION,
    geoname_id  INTEGER,
    geocode_src TEXT
);

CREATE TABLE reference (
    id   BIGINT PRIMARY KEY,
    text TEXT NOT NULL,
    hash TEXT
);

-- =========================================================================
-- Main fact table
-- =========================================================================

CREATE TABLE sighting (
    id                  BIGINT PRIMARY KEY,

    -- Provenance
    source_db_id        BIGINT NOT NULL REFERENCES source_database(id),
    source_record_id    TEXT,
    origin_id           BIGINT REFERENCES source_origin(id),
    origin_record_id    TEXT,

    -- Date / time (stored as TEXT for parity with SQLite — many records
    -- have partial or non-ISO dates we can't safely cast to TIMESTAMP)
    date_event          TEXT,
    date_event_raw      TEXT,
    date_end            TEXT,
    time_raw            TEXT,
    timezone            TEXT,

    -- Reporting
    date_reported       TEXT,
    date_posted         TEXT,

    -- Location
    location_id         BIGINT REFERENCES location(id),

    -- Description
    summary             TEXT,
    description         TEXT,

    -- Observation details
    shape               TEXT,
    color               TEXT,
    size_estimated      TEXT,
    angular_size        TEXT,
    distance            TEXT,
    duration            TEXT,
    duration_seconds    INTEGER,
    num_objects         INTEGER,
    num_witnesses       INTEGER,
    sound               TEXT,
    direction           TEXT,
    elevation_angle     TEXT,
    viewed_from         TEXT,

    -- Witness info
    witness_age         TEXT,
    witness_sex         TEXT,
    witness_names       TEXT,

    -- Classification
    hynek               TEXT,
    vallee              TEXT,
    event_type          TEXT,
    svp_rating          TEXT,

    -- Resolution
    explanation         TEXT,
    characteristics     TEXT,

    -- Weather / conditions
    weather             TEXT,
    terrain             TEXT,

    -- References
    source_ref          TEXT,
    page_volume         TEXT,

    -- Metadata
    notes               TEXT,
    raw_json            TEXT,
    created_at          TIMESTAMPTZ DEFAULT NOW()
);

-- =========================================================================
-- Auxiliary fact tables
-- =========================================================================

CREATE TABLE attachment (
    id          BIGINT PRIMARY KEY,
    sighting_id BIGINT NOT NULL REFERENCES sighting(id),
    url         TEXT,
    file_type   TEXT,
    description TEXT
);

CREATE TABLE sighting_reference (
    sighting_id  BIGINT NOT NULL REFERENCES sighting(id),
    reference_id BIGINT NOT NULL REFERENCES reference(id),
    PRIMARY KEY (sighting_id, reference_id)
);

CREATE TABLE duplicate_candidate (
    id               BIGINT PRIMARY KEY,
    sighting_id_a    BIGINT NOT NULL REFERENCES sighting(id),
    sighting_id_b    BIGINT NOT NULL REFERENCES sighting(id),
    similarity_score DOUBLE PRECISION,
    match_method     TEXT,
    status           TEXT DEFAULT 'pending',
    resolved_at      TEXT,
    UNIQUE (sighting_id_a, sighting_id_b)
);

CREATE TABLE sentiment_analysis (
    id               BIGINT PRIMARY KEY,
    sighting_id      BIGINT NOT NULL UNIQUE REFERENCES sighting(id),
    vader_compound   DOUBLE PRECISION,
    vader_positive   DOUBLE PRECISION,
    vader_negative   DOUBLE PRECISION,
    vader_neutral    DOUBLE PRECISION,
    emo_joy          INTEGER DEFAULT 0,
    emo_fear         INTEGER DEFAULT 0,
    emo_anger        INTEGER DEFAULT 0,
    emo_sadness      INTEGER DEFAULT 0,
    emo_surprise     INTEGER DEFAULT 0,
    emo_disgust      INTEGER DEFAULT 0,
    emo_trust        INTEGER DEFAULT 0,
    emo_anticipation INTEGER DEFAULT 0,
    text_source      TEXT,
    text_length      INTEGER,
    created_at       TIMESTAMPTZ DEFAULT NOW()
);

-- The historic-date-corrections audit table from the unmerged-work branch.
-- Carried over so the migrated DB has the same shape as the canonical SQLite.
CREATE TABLE date_correction (
    id              BIGINT PRIMARY KEY,
    sighting_id     BIGINT NOT NULL REFERENCES sighting(id),
    source_name     TEXT NOT NULL,
    original_date   TEXT,
    corrected_date  TEXT,
    correction_type TEXT NOT NULL,
    reason          TEXT,
    created_at      TIMESTAMPTZ DEFAULT NOW()
);

-- =========================================================================
-- Indexes (named the same as in SQLite for easy diffing)
-- =========================================================================

-- sighting
CREATE INDEX idx_sighting_date          ON sighting(date_event);
CREATE INDEX idx_sighting_source        ON sighting(source_db_id);
CREATE INDEX idx_sighting_origin        ON sighting(origin_id);
CREATE INDEX idx_sighting_shape         ON sighting(shape);
CREATE INDEX idx_sighting_hynek         ON sighting(hynek);
CREATE INDEX idx_sighting_vallee        ON sighting(vallee);
CREATE INDEX idx_sighting_type          ON sighting(event_type);
CREATE INDEX idx_sighting_location      ON sighting(location_id);
CREATE INDEX idx_sighting_source_record ON sighting(source_db_id, source_record_id);
CREATE INDEX idx_sighting_source_date   ON sighting(source_db_id, date_event);
-- idx_sighting_source_ref is intentionally omitted: at least one source_ref
-- value exceeds PostgreSQL's btree key size limit (2704 bytes), and the web
-- app never queries by source_ref. If a future query needs it, use a function
-- index like CREATE INDEX ... ON sighting(MD5(source_ref)) for exact lookups.

-- location
CREATE INDEX idx_location_country    ON location(country);
CREATE INDEX idx_location_city       ON location(city);
CREATE INDEX idx_location_coords     ON location(latitude, longitude);
CREATE INDEX idx_location_city_state ON location(city, state);

-- duplicate_candidate
CREATE INDEX idx_duplicate_status ON duplicate_candidate(status);
-- v0.7: single-column btree on each side of the pair so the
-- /api/sighting/<id> UNION ALL lookup can use an index for each
-- equality scan instead of falling back to a seqscan over the OR.
CREATE INDEX idx_duplicate_a ON duplicate_candidate(sighting_id_a);
CREATE INDEX idx_duplicate_b ON duplicate_candidate(sighting_id_b);

-- sentiment_analysis
CREATE INDEX idx_sentiment_compound ON sentiment_analysis(vader_compound);
CREATE INDEX idx_sentiment_sighting ON sentiment_analysis(sighting_id);

-- date_correction
CREATE INDEX idx_date_correction_sighting ON date_correction(sighting_id);
CREATE INDEX idx_date_correction_type     ON date_correction(correction_type);

-- =========================================================================
-- App-only indexes (added beyond what SQLite has, for PG-specific wins)
-- =========================================================================

-- Speeds up the LIKE/ILIKE search on description and summary by enabling
-- trigram similarity. Requires the pg_trgm extension. Massive win for the
-- /api/search endpoint (no more full table scans for substring matches).
CREATE EXTENSION IF NOT EXISTS pg_trgm;

CREATE INDEX idx_sighting_description_trgm
    ON sighting USING gin (description gin_trgm_ops);

CREATE INDEX idx_sighting_summary_trgm
    ON sighting USING gin (summary gin_trgm_ops);
